config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :trainers
  resources :clients
  resources :assessments
  
  get 'clients/:id/stats', to: 'clients#stats', as: 'client/stats'
  
  get 'clients/index', to: 'clients#index', as: 'clients/search'
  
  root 'pages#home'
  
  
  

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :client
  validates :blood_pressure, presence: true
  validates :resting_pulse, presence: true
  validates :fat_bicep, :fat_tricep, :fat_subscab, :fat_iliac, :fat_thigh, presence: true, numericality: true
  validates :weight, presence: true, numericality: true
  validates :stretch, presence: true, numericality: true
  validates :step_test_1, :step_test_2, :step_test_3, presence: true
  validates :situps, :pushups, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :trainer
  has_many :assessments
  
  validates :name, presence: true
  validates :phone_number, presence: true, uniqueness: true,
                 numericality: true,
                 length: { minimum: 10, maximum: 10 } 
                 
  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end           
  
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]
  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new(client_id: params[:client_id])
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)
    @assessment.fat_total = calculate_fat
    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    @assessment.fat_total = calculate_fat
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:weight, :situps, :pushups, :heartrate, :bodyfat, :client_id,
      :blood_pressure, :resting_pulse, :fat_bicep, :fat_tricep, :fat_subscab, :fat_iliac, :fat_thigh, 
      :fat_total, :stretch, :step_test_1, :step_test_2, :step_test_3)
    end
    
    def calculate_fat 
      return ((@assessment.fat_bicep.to_f + @assessment.fat_tricep.to_f + @assessment.fat_subscab.to_f + @assessment.fat_iliac.to_f + @assessment.fat_thigh.to_f) / 5).to_f
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy, :stats]

  # GET /clients
  # GET /clients.json
  def index
    @clients = if params[:search_request]
      Client.where('lower(name) LIKE ?', "%#{(params[:search_request]).downcase}%")
    else
      Client.all
    end
  end

  def search
    @clients = Client.search(params[:search_request])
  end
  # GET /clients/1
  # GET /clients/1.json
  def show
  end
  
  def stats
    @assessments = @client.assessments.all
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
      #  format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end
    
    def set_clients
      @clients
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :surname, :phone_number, :search_request)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :surname, :username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
  def random_chartkick_id
    return 'chart-#'+(Random.rand(10000)).to_s
  end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/assessments/_form.html.erb
<%= render 'shared/errors', obj: @assessment %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@assessment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
    <div class="pressure-pulse">
      <h4 align="center">Blood pressure and Pulse</h4>
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label :blood_pressure %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :blood_pressure, class: "form-control", placeholder: "eg. 120/90", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label :resting_pulse %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :resting_pulse, class: "form-control", placeholder: "eg. 110/70", autofocus: true %>
        </div>
      </div>
      
    </div>
     
    
    <div class="fat-weight">
      
      <h4 align="center">Body Fat</h4>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Bicep" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :fat_bicep, class: "form-control", placeholder: "Bicep", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Tricep" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :fat_tricep, class: "form-control", placeholder: "Tricep", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Subscab" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :fat_subscab, class: "form-control", placeholder: "Subscab", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Iliac" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :fat_iliac, class: "form-control", placeholder: "Iliac", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Thigh" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :fat_thigh, class: "form-control", placeholder: "Thigh", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label :weight %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :weight, class: "form-control", placeholder: "Weight", autofocus: true %>
        </div>
      </div>
      
    </div> 
     
    <div class="fitness-test">
      <h4 align="center">Fitness Test</h4>
       
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Stretch" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :stretch, class: "form-control", placeholder: "Stretch", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label "Step Test" %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :step_test_1, class: "form-control", placeholder: "Step test 1", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
        </div>
        <div class="col-md-4">
          <%= f.text_field :step_test_2, class: "form-control", placeholder: "Step test 2", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
        </div>
        <div class="col-md-4">
          <%= f.text_field :step_test_3, class: "form-control", placeholder: "Step test 3", autofocus: true %>
        </div>
      </div>
       
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label :situps %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :situps, class: "form-control", placeholder: "Amount of situps" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-3 col-md-offset-2">
          <%= f.label :pushups %><br>
        </div>
        <div class="col-md-4">
          <%= f.text_field :pushups, class: "form-control", placeholder: "Amount of pushups" %>
        </div>
      </div>
      
    </div>  
    
    <%= f.hidden_field :client_id, value: @assessment.client_id %>
      
  <div class="form-group">
    <div class="col-md-offset-3 col-md-6">
      <%= f.submit class: 'btn btn-primary btn-lg full-btn' %>
    </div>
  </div>
      
    <% end %>

  </div>
</div>

app/views/assessments/edit.html.erb
<div class="heading">
  <h1>Editing Assessment</h1>
</div>

<%= render 'form' %>
<div class="col-md-6 col-md-offset-3">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Cancel', assessment_path(@assessment), class: "btn btn-warning btn-lg full-btn" %>
  </div>
</div>

app/views/assessments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assessments</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Situps</th>
      <th>Pushups</th>
      <th>Client ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= assessment.weight %></td>
        <td><%= assessment.situps %></td>
        <td><%= assessment.pushups %></td>
        <td><%= assessment.client_id %></td>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assessment', new_assessment_path %>

app/views/assessments/new.html.erb
<div class="heading">
  <h1>New Assessment </h1>
</div>

<%= render 'form' %>

<div class="col-md-6 col-md-offset-3">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Cancel', client_path(Client.find(params[:client_id])), class: "btn btn-warning btn-lg full-btn" %>
  </div>
</div>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>
<% @client = Client.find_by(params[:client_id]) %>
<div class="heading">
  <h1>
    Assessment of <%= @client.name + " " + @client.surname %>
  </h1>
  <h1>
    <%= @assessment.created_at.strftime("%a, %d %b %Y") %>
  </h1>
</div>

<div class="table-responsive col-md-8 col-md-offset-2">
  <table class="table table-bordered">
    <thead>
      <th class="col-md-4">Test</th>
      <th class="col-md-4">Value</th>
    </thead>
    <tbody>
      <tr>
        <td>Blood Pressure</td> 
        <td><%= @assessment.blood_pressure %></td>
      </tr>
      <tr>
        <td>Resting Pulse</td>
        <td><%= @assessment.resting_pulse %></td>
      </tr>
      <tr>
        <td>Bicep fat</td>
        <td><%= @assessment.fat_bicep %></td>
      </tr>
      <tr>
        <td>Tricep fat</td>
        <td><%= @assessment.fat_tricep %></td>
      </tr>
      <tr>
        <td>Subscab fat</td>
        <td><%= @assessment.fat_subscab %></td>
      </tr>
      <tr>
        <td>Iliac fat</td>
        <td><%= @assessment.fat_iliac %></td>
      </tr>
      <tr>
        <td>Thigh fat</td>
        <td><%= @assessment.fat_thigh %></td>
      </tr>
      <tr>
        <td>Total fat</td>
        <td><%= @assessment.fat_total %>%</td>
      </tr>
      <tr>
        <td>Weight</td>
        <td><%= @assessment.weight %></td>
      </tr>
      <tr>
        <td>Stretch test</td>
        <td><%= @assessment.stretch %>cm</td>
      </tr>
      <tr>
        <td>Step test</td>
        <td><%= @assessment.step_test_1 + " " + @assessment.step_test_2 + " " + @assessment.step_test_3 %></td>
      </tr>
      <tr>
        <td>Situps</td>
        <td><%= @assessment.situps %></td>
      </tr>
      <tr>
        <td>Pushups</td>
        <td><%= @assessment.pushups %></td>
      </tr>
      
    </tbody>
  </table>
</div>

<div class="col-md-8 col-md-offset-2">
  <div class="col-md-4">
    <%= link_to 'Back', client_path(Client.find_by(params[:client_id])), class: "btn btn-primary btn-lg full-btn" %>
  </div>
  <div class="col-md-4">
    <%= link_to 'Edit', edit_assessment_path(@assessment), class: "btn btn-warning btn-lg full-btn" %>
  </div>
  <div class="col-md-4">
    <%= link_to 'Delete', assessment_path(@assessment), method: :delete, 
          data: { confirm: "Are you sure you want to delete the client?"}, class: "btn btn-lg btn-danger full-btn" %>  
  </div>
</div>

app/views/clients/_form.html.erb
  <%= render 'shared/errors', obj: @client %>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@client, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Client name", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :surname %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :surname, class: "form-control", placeholder: "Client surname" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :phone_number %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :phone_number, class: "form-control", placeholder: "eg. 0713344309" %>
          </div>
        </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
              <%= f.submit class: 'btn btn-primary btn-lg full-btn' %>
            </div>
          </div>
          
        </div>
      </div>
  <% end %>

app/views/clients/edit.html.erb
<div class="heading">
  <h1>Editing Client</h1>
</div>

<%= render 'form' %>

<div class="col-md-4 col-md-offset-4">
  <%= link_to 'Cancel', client_path(@client), class: "btn btn-warning btn-lg full-btn" %>
</div>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="heading">
  <h1 align="center">Listing Clients</h1>
</div>
<div class="col-md-12" style="padding-bottom: 20px">
 <%= form_tag(clients_path, method: :get) do %>
  <div class="col-md-6 col-md-offset-4">
    <div class="input-group col-md-8">
      <%= text_field_tag :search_request, params[:search_request], class: "form-control", placeholder: "Search clients" %>
      <span class="input-group-btn">
        <%= submit_tag 'Search',name: nil, class: "btn btn-default"%>
      </span>
        <% end %>
    </div>
  </div>
</div>
  

  <div class="row">
    <div class="col-md-12">
      
      <% @clients.each do |client| %>
          <div class="col-md-6">
            <div class="well well-sm client-preview">
              <% names = client.name + ' ' + client.surname %>
             
              <h2><%= link_to names, client_path(client), class: "client-name" %></h2>
              <h4><%= pluralize(client.assessments.count, "assessment")  %></h4>
              <small>
                <%= "Last assessment: " + time_ago_in_words(client.assessments.last.created_at) + " ago" if client.assessments.any?  %>
              </small>
            </div>
          </div>
      <% end %>
    </div>
    
  </div>

app/views/clients/new.html.erb
<div class="heading">
  <h1 align="center">New Client</h1>
</div>

<%= render 'form' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-6 col-md-offset-3">
  
  <div class="client-preview">
    <h1><%= @client.name + ' ' + @client.surname%></h1>
    <h5><%= @client.phone_number %></h5>
    
    <div class="col-md-12">
      <button data-toggle="collapse" data-target="#client-actions" class="btn btn-lg btn-info full-btn">Actions</button>
    </div>
    <div id="client-actions" class="collapse">
      <div class="row">
        <div class="client-action col-md-4">
          <%= link_to 'New assessment', new_assessment_path(:client_id => @client.id), class: "btn btn-lg btn-success full-btn" %>
        </div>
        <div class="client-action col-md-4">
          <%= link_to 'Edit client info', edit_client_path(@client), class: "btn btn-lg btn-primary full-btn" %> 
        </div>
        <div class="client-action col-md-4">
          <%= link_to 'Delete client', client_path(@client), method: :delete, 
          data: { confirm: "Are you sure you want to delete the client?"}, class: "btn btn-lg btn-danger full-btn" %>  
        </div>
        <div class="col-md-12">
          <%= link_to 'View Stats', client_stats_path(@client), class: "btn btn-lg btn-info full-btn" %>  
        </div>
      </div>
    </div>

    <div class="col-md-12">
    <% if @client.assessments %>
      <div class="table-responsive" style="margin-top: 10px">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Assessment</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            <% num = @client.assessments.count %>
            <% @client.assessments.reverse.each do |a| %>
              <tr>
                <td class="col-md-3"><%= link_to num, assessment_path(a), class: "btn btn-info btn-md half-btn" %></td>
                <td class="col-md-3"><%= a.created_at.strftime("%d %b %Y") %></td>
              </tr>
              <% num = num - 1 %>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <h3>Client has no assessments</h3>
    <% end %>
    </div>
    
    
  </div>
</div>

app/views/clients/stats.html.erb
<div class="heading">
  <h1 align="center">Statistics for <%= @client.name %>'s previous assessments</h1>
</div>

<% Chartkick.options[:html] = '<div id="%{id}" style="height: %{height};">Loading...</div>' %>

<div class="row">
  <div class="col-md-6 col-graph">
    <h3 align="center" class="graph-heading">Weight</h3>
    <%= line_chart @assessments.pluck(:created_at, :weight), xtitle: "Assessment",
    ytitle: "Weight (kg)", id: random_chartkick_id, width: "100%", colors: ["#396ab1", "#999"] %>
  </div>
  <div class="col-md-6 col-graph">
    <h3 align="center" class="graph-heading">Body fat</h3>
    <%= line_chart @assessments.pluck(:created_at, :fat_total), xtitle: "Assessment", 
    ytitle: "Total body fat %", id: random_chartkick_id, width: "100%", colors: ["#cc2529", "#999"] %>
  </div>
  <div class="col-md-6 col-graph">
    <h3 align="center" class="graph-heading">Sit-ups</h3>
    <%= line_chart @assessments.pluck(:created_at, :situps), xtitle: "Assessment", 
    ytitle: "Sit-ups per minute", id: random_chartkick_id, width: "100%", colors: ["#3e9651", "#999"], curve: false %>
  </div>
  <div class="col-md-6 col-graph">
    <h3 align="center" class="graph-heading">Push-ups</h3>
    <%= line_chart @assessments.pluck(:created_at, :pushups), xtitle: "Assessment", 
    ytitle: "Push-ups (max)", id: random_chartkick_id, width: "100%", colors: ["#da7c30", "#999"], curve: false %>
  </div>
  <div class="col-md-4 col-md-offset-4">
    <%= link_to 'Back', client_path(@client), class: "btn btn-primary btn-lg full-btn" %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Gym App", root_path, class: "logo" %>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "View Clients", clients_path, class: "nav-link" %></li>
          <li><%= link_to "New Client", new_client_path, class: "nav-link" %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
      
      
      
    </div><!-- /.container-fluid -->
    
  </nav>
</div>

app/views/pages/home.html.erb
<h1 align="center">Gym App</h1>

<div class="container">
  <div class="jumbotron">
    
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4 col-home">
          <h3><%= pluralize(Client.count, "Client") %></h3>
          <%= link_to "View Clients", clients_path, class: "btn btn-primary btn-lg client-action" %>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.surname %></td>
        <td><%= trainer.username %></td>
        <td><%= trainer.password %></td>
        <td><%= trainer.email %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @trainer.surname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @trainer.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @trainer.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.email %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>